### ISSUE TITLE
Error use of internal package not allowed

### ISSUE THREAD

**Issue by baksosapi** [ribice/gorsk#33]
Trying to run ``` go run cmd/api/main.go ```, but get problem with **"internal package not allowed"**
I clone project under $GOPATH/src, then
```=> export GOPATH=/Volumes/MacHD/Myproject/GoLand
=> ~/go/bin/dep ensure -v
=> go run cmd/api/main.go
cmd/api/main.go:44:2: use of internal package not allowed
cmd/api/main.go:45:2: use of internal package not allowed
cmd/api/main.go:36:2: use of internal package not allowed
cmd/api/main.go:46:2: use of internal package not allowed
cmd/api/main.go:47:2: use of internal package not allowed 
```

After removed  github.com/ribice from import in all go files, so
``` 
import (
        ...
	"gorsk/internal"
        ...
)
```
Everything goes well.

**Comment by ribice** [comment]
Is the project located in `$GOPATH/src/github.com/ribice/gorsk` or `$GOPATH/src` ?

**Comment by baksosapi** [comment]
the project in 
```
=> echo $GOPATH
/Volumes/MacHD/Myproject/GoLand
=> pwd
/Volumes/MacHD/Myproject/GoLand/src/gorsk
=> ls
Gopkg.lock   Gopkg.toml   LICENSE      README.MD    cmd          coverage.txt internal     profile.out  test.sh      vendor
```

**Comment by ribice** [comment]
Did you do step 1 from readme?

`To use Gorsk as a starting point of a real project whose package name is something like github.com/author/project, move the directory $GOPATH/github.com/ribice/gorsk to $GOPATH/github.com/author/project and do a global replacement of the string github.com/ribice/gorsk with github.com/author/project.`

**Comment by ribice** [comment]
I just tested, and this is related to your path. Make sure to follow the steps correctly. If you have issues let me know.
