### ISSUE TITLE
Move config test files from files directory

### ISSUE THREAD

**Issue by ribice** [ribice/gorsk#4]
When testing config.go, config.invalid.yml and config.testdata.yml are being used.

They are located at same directory as other config files, which should not be the case due to clutter. They need to be moved to separate folder, e.g. testdata.

**Comment by julienkosinski** [comment]
@ribice Is that not useful to do in the end?

**Comment by ribice** [comment]
It is, I will do this and few other changes during the weekend. However I'll change the project layout a bit, not directly related to this issue.

**Comment by julienkosinski** [comment]
Oh, great, thenk you for all!! :D
