### ISSUE TITLE
The /swaggerui endpoint returns a 404 Not Found Error

### ISSUE THREAD

**Issue by aalhour** [ribice/gorsk#41]
I have setup the server according to the docs and running it normally via: `go run cmd/api/main.go`. Requesting the `/swaggerui` endpoint returns the following JSON error message:

```
$ curl http://localhost:8080/swaggerui/ 
"code=404, message=Not Found"
```

The error occurs regardless of the trailing `/` character in the URL.

**Comment by ribice** [comment]
Checked out to master, ran using `go run cmd/api/main.go`

![image](https://user-images.githubusercontent.com/5403700/45620003-9cd8d580-ba7b-11e8-96c2-bbe5c48dbb1d.png)

**Comment by aalhour** [comment]
Weird, I am also running it on master. The only thing I changed was the PostgreSQL psn in the `cmd/migrations/main.go`.

I ran the following commands from outside the `cmd/api/` directories and got different errors, here are the logs:
```
$ go run cmd/api/main.go 

{"time":"2018-09-17T15:50:04.810647465+02:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/swaggerui","status":304, "latency":65190,"latency_human":"65.19µs","bytes_in":0,"bytes_out":0}
{"time":"2018-09-17T15:50:04.885457765+02:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/swagger-ui.css","status":500, "latency":32661,"latency_human":"32.661µs","bytes_in":0,"bytes_out":29}
{"time":"2018-09-17T15:50:04.885919902+02:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/swagger-ui-bundle.js","status":500, "latency":26716,"latency_human":"26.716µs","bytes_in":0,"bytes_out":29}
{"time":"2018-09-17T15:50:04.886157178+02:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/swagger-ui-standalone-preset.js","status":500, "latency":15142,"latency_human":"15.142µs","bytes_in":0,"bytes_out":29}
{"time":"2018-09-17T15:50:04.896911361+02:00","id":"","remote_ip":"127.0.0.1","host":"localhost:8080","method":"GET","uri":"/swagger-ui-standalone-preset.js","status":500, "latency":49556,"latency_human":"49.556µs","bytes_in":0,"bytes_out":29}
```

How did you setup your entire project? I got your package using `go get`.

**Comment by ribice** [comment]
You should run it from root folder, using `go run cmd/api/main.go` and access `localhost:8080/swaggerui/` (with trailing slash).

**Comment by aalhour** [comment]
It works. Thanks!

**Comment by rutgervandeelen** [comment]
I encountered the same issue. Now it works. 
Perhaps it is an idea to add this to the readme?

```
GET /swaggerui/: launches swaggerui in browser (i.e. with a trailing forward slash)
```

**Comment by ribice** [comment]
Added to Readme. Thanks!
