### ISSUE TITLE
Questions about routes

### ISSUE THREAD

**Issue by julienkosinski** [ribice/gorsk#49]
I think this would be more logical to have routes like below because user should be singular when manipulating only one entry don't you think?

```
POST /login: accepts username/passwords and returns jwt token and refresh token
GET /refresh/:token: refreshes sessions and returns jwt token
GET /me: returns info about currently logged in user
GET /swaggerui/: launches swaggerui in browser
GET /v1/users: returns list of users
GET /v1/user/:id: returns single user
POST /v1/user: creates a new user
PATCH /v1/user/:id/password: changes password for a user
DELETE /v1/user/:id: deletes a user
```

Also, I'm wondering about route if version should be on every routes or not.

**Comment by ribice** [comment]
Both of these are opinionated and depending on who you ask, might be a good or bad solution..

**Comment by julienkosinski** [comment]
Thank you for your response :-).
