### ISSUE TITLE
Cookie based authentication instead of jwt.

### ISSUE THREAD

**Issue by frederikhors** [ribice/gorsk#53]
Is there a way to have cookie based authentication instead of jwt one? Also because of this: 
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

**Comment by ribice** [comment]
You're fast :). (opening issue a minute after it was posted on HN).

I avoid using JWT for sessions, and use K/V store (Redis) + JWT for that purpose in my projects.

Since this is just an example project, and is supposed to be simple, I'd rather not use Redis or something similar in it.

**Comment by frederikhors** [comment]
> You're fast :). (opening issue a minute after it was posted on HN).

I do not know anything about HN.

> I avoid using JWT for sessions, and use K/V store (Redis) + JWT for that purpose in my projects.
> Since this is just an example project, and is supposed to be simple, I'd rather not use Redis or something similar in it

Maybe a post / tutorial how to use it with Gorsk?

**Comment by ribice** [comment]
You can refer to [chisk](https://github.com/ribice/chisk), most namely [session.go](https://github.com/ribice/chisk/blob/master/pkg/session/session.go).
