### ISSUE TITLE
Viper for configuration management

### ISSUE THREAD

**Issue by checkaayush** [ribice/gorsk#54]
How about using https://github.com/spf13/viper for configuration management? We won't be restricted to YAML files for configurations.

Would be happy to contribute if this looks like a suitable enhancement.

P.S.: Loved gorsk. Saved me a lot of effort in standardising things. :+1: :)

**Comment by ribice** [comment]
Hi @checkaayush, I'd rather avoid using `viper` for two reasons:

1. The simpler the project the better.
2. I prefer having less dependencies. Although at the end it still counts as 1 instead of yaml,  yaml library has no external dependencies while viper has many of them.

Thanks!
