### ISSUE TITLE
Keep track on user actions

### ISSUE THREAD

**Issue by julienkosinski** [ribice/gorsk#62]
My problem might be basic, I'm new to go, sorry.

I'd like to add in the database multiple common field defined in `pkg/utl/model/model.go` like that:
```go
// Base contains common fields for all tables
type Base struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt time.Time `json:"deleted_at,omitempty" pg:",soft_delete"`
	CreatedBy int `json:"created_by"`
	UpdatedBy int `json:"updated_by"`
	DeletedBy int `json:"deleted_by,omitempty"`
}
```

The idea is fill the fields with the ID of the authenticated user like it fills times with the use of go-pg hooks functions. 

So still in `pkg/utl/model/model.go` I'd like to be able to do something like:
```go
// BeforeInsert hooks into insert operations, setting createdAt and updatedAt to current time
func (b *Base) BeforeInsert(_ orm.DB) error {
	now := time.Now()
	b.CreatedAt = now
	b.UpdatedAt = now

	b.CreatedByID = contextUserID
	b.UpdatedByID = contextUserID

	return nil
}

// BeforeUpdate hooks into update operations, setting updatedAt to current time
func (b *Base) BeforeUpdate(_ orm.DB) error {
	b.UpdatedAt = time.Now()

	b.UpdatedByID = contextUserID

	return nil
}

// BeforeUpdate hooks into delete operations
func (b *Base) BeforeDelete(_ orm.DB) error {
	
	b.DeletedByID = contextUserID

	return nil
}
```

In this file how can I access `echo.Context.Get("id")` to fill `contextUserID`?

(Merry Christmas ;))

**Comment by ribice** [comment]
Where do you want to log it, stdout?

`c.Get("id")` should already return you user id.

**Comment by julienkosinski** [comment]
Thank you very much for your response. My issue was totally unreadable, I edited it. Is this more understandable?

**Comment by ribice** [comment]
Since `gorsk` uses echo instead of stdlib, you'd have to do something like this:

In jwt middleware, take `context.Context` out of `echo.Context`:

`ctx := c.Request.Context()`

Next, fill it in with data you need.

`ctx = context.WithValue(ctx, "id", user.ID)`

Then, in application service (`pkg/api/user` for example) pass the db value with Context. To do that, replace `return u.udb.Create(u.db, req)` with `return u.udb.Create(u.db.WithContext(c.Request.Context), req)`

Lastly, do the following change in BeforeInsert func:

```
func (b *Base) BeforeInsert(db orm.DB) error {
	now := time.Now()
	b.CreatedAt = now
	b.UpdatedAt = now

        ctx := db.Context()
	b.CreatedByID = ctx.Value("id")
	b.UpdatedByID =  ctx.Value("id")
	return nil
}
```

**Comment by julienkosinski** [comment]
@ribice Thank you very much for your help!

I'm getting an error I don't understand (because it seems defined...)
```
# github.com/ribice/gorsk/pkg/utl/middleware/jwt [github.com/ribice/gorsk/pkg/utl/middleware/jwt.test]
.\jwt.go:66: c.Request.Context undefined (type func() *http.Request has no field or method Context)
```

NB: It seems that I need a custom type to be lintproof:
`should not use basic type untyped string as key in context.WithValue (golint)`
I'm not skilled enough to understand what could be this collision here be doc says:
```
// The provided key must be comparable and should not be of type
// string or any other built-in type to avoid collisions between
// packages using context. Users of WithValue should define their own
// types for keys. To avoid allocating when assigning to an
// interface{}, context keys often have concrete type
// struct{}. Alternatively, exported context key variables' static
// type should be a pointer or interface.
```

**Comment by ribice** [comment]
1. `c.Request().Context()`
2.
```
type contextKey string
var (
    UserIDCtxToken = contextKey("auth-token")
)

ctx = context.WithValue(ctx, UserIDCtxToken, "id")
```

**Comment by ribice** [comment]
userIDCtxToken needs to be visible in other packages, so that you can use it in `model.go`

Again, since gorsk uses `echo` and not stdlib, it complicates things a bit. You need to do the following (before `return next(c)):

`c.SetRequest() = c.Request().WithContext(ctx)`

**Comment by julienkosinski** [comment]
```go
// BeforeInsert hooks into insert operations, setting createdAt and updatedAt to current time
func (b *Base) BeforeInsert(db orm.DB) error {
	type contextKey string

	var (
		userIDCtxToken = contextKey("auth-user-id")
	)

	now := time.Now()
	b.CreatedAt = now
	b.UpdatedAt = now

	ctx := db.Context()
	v := ctx.Value(userIDCtxToken)
	if v != nil {
		idUser := v.(int)
		b.CreatedByID = idUser
		b.UpdatedByID = idUser
	}
	return nil
}
```

Here is the values I'm getting debugging in Atom IDE, as you can see retrieving context is working and it contains the right value, extracting the value is not ok. `v` is nil but `ctx` contains the context with the right key/value in it.

```go
b: *model.Base
ctx: context.Context (*context.valueCtx)
	Context: context.Context (*context.cancelCtx)
	key: interface {} ("auth-user-id")
	val: interface {} (1)
db: orm.DB (*pg.DB)
now: time.Time
userIDCtxToken: "auth-user-id"
v: interface {} nil
~r1: error nil
```

Thanks and happy new year!

**Comment by ribice** [comment]
userIDCtxToken has to be the same variable (not same name), so you need to make it global.

**Comment by julienkosinski** [comment]
Thank you very much for all! It's working as expected now!
