### ISSUE TITLE
Pagination struct located into models directory

### ISSUE THREAD

**Issue by benjaminch** [ribice/gorsk#63]
Hello @ribice ,

First, thanks for this repo, it's really nice to have something to start with !

I have a question regarding `Pagination` struct and was wondering why its located into models directory?
To me pagination mechanism relates to API stuff and is not really to domain.
Is there any reason I am missing to have it here ?

https://github.com/ribice/gorsk/blob/master/pkg/utl/model/pagination.go

Thanks

**Comment by ribice** [comment]
Hi,

You are correct and I wanted to put it that way. Problem was it's used in database too, so this way it was simpler to re-use it.

For example: https://github.com/ribice/gorsk/blob/master/pkg/api/user/platform/pgsql/user.go

I'm very open to suggestions if you have them.

**Comment by benjaminch** [comment]
Hum ... I see, maybe it's not really needed in the database part. Is it ?
