### ISSUE TITLE
swagger.json doesn't sync with code

### ISSUE THREAD

**Issue by ElvisChiang** [ribice/gorsk#64]
## Reproduce

By using latest go-swagger
```
swagger generate spec -o assets/swaggerui/swagger.json --scan-models -b github.com/ribice/gorsk/pkg/api
```

check assets/swaggerui/swagger.json

**Comment by ribice** [comment]
Could you please make a PR with updated `swagger.json`? Thanks!

Also keep noted that swagger.json shouldn't be there, it should be generated by a CI/CD tool.

**Comment by ElvisChiang** [comment]
I'm quite new to golang and swagger, please have a look #65
