### ISSUE TITLE
microservice and docker

### ISSUE THREAD

**Issue by naraycitra** [ribice/gorsk#67]
Hi, please introduce my name is Naray Citra from Indonesia. I learned Golang since 2 weeks ago, same as you my programming experience is Java with SpringBoot :). I found your started kit by searching google :). I like your stater kit, but i still newbie in Golang, i have some questions for you. How we separate the pkg into microservice and containerized it? Can you give an example for that?

**Comment by ribice** [comment]
If you're quite new to Go, I'd recommend staying with monolith. If you want to make microservices and use monorepo, you would have multiple binaries located in `cmd` (e.g. `users`, `payment`) and the  same directory in pkg (e.g. `/pkg/users`/, `/pkg/payment`).

**Comment by naraycitra** [comment]
Thank you for your recommendation. If you don't mind, can you give us example on the read me how to make monorepo or microservice. The purpose is to enrich your stater kit.

**Comment by ribice** [comment]
https://en.wikipedia.org/wiki/Microservices

https://en.wikipedia.org/wiki/Monorepo
