### ISSUE TITLE
Using Gorsk

### ISSUE THREAD

**Issue by seydimomogueye** [ribice/gorsk#68]
Hi Mr Ribice,
My name is Mouhamed, I’m a software engineer and I’m new to Golang.
I decide to use it to build Restful API, and after few research on which framework to use, I found your GitHub repository about Gorsk. For me it’s an amazing work and I decided to use it.
But can I have more details about the workflow on gorsk for example the migrations. What is the best way to write them ? In the main file or create differences packages inside ? (I come from Django rest framework so please understand :))
Also can I have a project sample to explore before starting and doing messy things :).

**Comment by ribice** [comment]
Migrations are not supported with gorsk, use an external tool like `flywaydb`.
