### ISSUE TITLE
Docker and Go modules

### ISSUE THREAD

**Issue by checkaayush** [ribice/gorsk#70]
- I feel adding docker and docker-compose setup will make local development way easier and could replace the replace-all package steps while getting started.
- Also, how about using Go modules?

A makefile target can also be used instead of manual package name change. See [this](https://github.com/snowzach/gorestapi#relocation).
 
Would be happy to submit PRs if above sound useful. 

P.S.: Nice work on v2 👍

**Comment by ribice** [comment]
Both would be good to do!

**Comment by ribice** [comment]
Added GoModules via #84
