### ISSUE TITLE
go get https://github.com/ribice/gorsk  returning an error

### ISSUE THREAD

**Issue by johnzon** [ribice/gorsk#71]
Go Version : 1.12
Os : MACOS (Linux)

I ran go get https://github.com/ribice/gorsk and got this error
https:/github.com/ribice/gorsk: https:/github.com/ribice/gorsk: invalid import path: malformed import path "https:/github.com/ribice/gorsk": invalid char ':
Am I missing something. I am a go starter running go version 1.12

**Comment by checkaayush** [comment]
@johnzon Try without the leading `https://`.
