### ISSUE TITLE
Just checking

### ISSUE THREAD

**Issue by vsoch** [ribice/gorsk#75]
Hey just wanted to check that you meant to have this here!

https://github.com/ribice/gorsk/blob/09b0ac849f19bbaa086139743527eb941c3c7c2b/cmd/api/conf.local.yaml#L4

If yes, then we're good, was just browsing and wanted to double check!

**Comment by ribice** [comment]
Yes, I'm totally cool with that as it's a free database plan and eases testing for user's of gorsk.
