### ISSUE TITLE
ENVIRONMENT_NAME not found in the code

### ISSUE THREAD

**Issue by buscando** [ribice/gorsk#87]
Hi

I cannot see where ENVIRONMENT_NAME is use id. I can see JWT_SECRET user as well as "psn" (DATABASE_URL) in the code
it seem setting ENVIRONMENT_NAME to "dev" it is not working. 

I am having certificate error like I am in PROD. 
go: downloading github.com/segmentio/encoding v0.1.10
pkg/api/auth/auth.go:8:2: found packages auth (auth.go) and gorsk (company.go) in /home/go/github.com/buscando/gocar
../../../pkg/mod/github.com/go-pg/pg/v9@v9.1.5/pgjson/json.go:7:2: github.com/segmentio/encoding@v0.1.10: 
Get "https://storage.googleapis.com/proxy-golang-org-prod/ xxx": x509: **certificate signed by unknown authority**

Any help is appreciated

Thank you
Marcelo

**Comment by ribice** [comment]
It seems to be a dependency issue with go-pg. I've updated dependencies in https://github.com/ribice/gorsk/commit/af20bef797543223550bda70f1fca5b4687c31f4.

Please report if the issue persists.
