### ISSUE TITLE
Readme inconsistency: Model files at root level vs pkg/utl/model

### ISSUE THREAD

**Issue by ifo20** [ribice/gorsk#88]
README references `pkg/utl/model` folder, but it seems such files were moved to root level in https://github.com/ribice/gorsk/commit/d89f430e7144c7af9c84293f5acc786d3ba97866

I was wondering if this (having the files at root level) is generally the preferred approach, or if it's better to use the folder as suggested in the readme?

> Inside pkg/utl/model create a new file named car.go. Inside put your entity (struct), and methods on the struct if you need them.

**Comment by ribice** [comment]
Good catch!

I put it at root, following suggestions from [HERE](https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1).
